### PR TITLE
Tweaks to ado_workitems_to_github_issues.ps1

### PR DESCRIPTION
**Pull request by BruceHaley**
### Changes
- Create a tag on the ADO work item saying it's been copied to GitHub
- Create a comment on the ADO work item giving a link to the GitHub item it was coped to
- Improve authentication using environment vars instead of logins. Logins want to be interactive and can be buggy
- Change WI query to 
  - Exclude work items tagged as already copied
  - Exclude work items with state "Done", etc.
- Report total items copied
- Add `-Encoding ASCII` to file writes. Default is Unicode. Our GitHub repos are not set up for Unicode text in issue and comment bodies.

### CODE REVIEW

**Comment by joshjohanning** [comment]
Nice! Thank you for the pull request @BruceHaley. A lot of great enhancements here! 

I will get back to you soon after my review 😄 

I might suggest some of these be put behind flags (ie: to ignore done items, adding a comment in ADO (which is awesome by the way)), but my initial look through 👍

**Comment by BruceHaley** [comment]
Glad you like it. Feel free to make any modifications you see fit.

**Review by joshjohanning — APPROVED** [review]

**Comment by joshjohanning** [comment]
I made some small tweaks, like adding bools for `ado_migrate_closed_workitems` and `ado_production_run` (for adding tag+comment on ado work item after migration).

Thank you for your contributions! 🎉 🚀

**Comment by joshjohanning** [comment]
In this PR, I changed it from `gh_add_ado_comments` to `gh_migrate_ado_comments`

But then when updating the readme, I didn't like it as much since it's not really migrating comments, it's just adding it as a section in GitHub. In a subsequent commit, I reverted that particular change :).

**Pull request merged**
